### ISSUE TITLE
TargetingKey in EvaluationContext is not converted

### ISSUE THREAD

**Issue by augustinasrce** [open-feature/ruby-sdk-contrib#40]
Since [EvaluationContext](https://github.com/open-feature/ruby-sdk/blob/27b2dab4fed0b348d0575c0909d4beeea376b27d/lib/open_feature/sdk/evaluation_context.rb#L8-L10) converts symbols to string 

```
      def initialize(**fields)
        @fields = fields.transform_keys(&:to_s)
      end
```

following [line](https://github.com/open-feature/ruby-sdk-contrib/blob/cb339983bf1e339255a252905c60f4d2c59ff758/providers/openfeature-flagd-provider/lib/openfeature/flagd/provider/client.rb#L101) doesn't work as intended

`fields["targetingKey"] = fields.delete(:targeting_key)`

**Comment by beeme1mr** [comment]
Hey @augustinasrce, thanks for reporting this issue. Would you be able to provide a fix? FYI @maxveldink

**Comment by augustinasrce** [comment]
Hey, yes! I'll cover it with some specs and raise a pr, probably today.

**Comment by maxveldink** [comment]
Thank you for fixing this! I'll make a release this morning
